#!/usr/bin/env bash
#
# Wholos — the one deploy entry point. Run it from anywhere in the repo.
#
#   ./deploy.sh              hosting only (the common case)
#   ./deploy.sh hub          rebuild the marketing hub, then hosting
#   ./deploy.sh app          typecheck + build the PWA, then hosting
#   ./deploy.sh server       Cloud Run only
#   ./deploy.sh all          app + hub + hosting + server
#
# It exists because the two things below have each cost a live outage, and
# neither announces itself at deploy time.
#
#   1. --set-secrets REPLACES the entire secret set. A server deploy that
#      listed ANTHROPIC_API_KEY alone silently dropped OPENAI_API_KEY and
#      LEONARDO_API_KEY; the service came up healthy and only /image and
#      /phrase started answering 503 no_leonardo_key / no_openai_key, which
#      reads like a billing problem and is not one. This script always uses
#      --update-secrets with all three, and verifies them after deploying.
#
#   2. On Git Bash, MSYS rewrites a /-leading argument into a Windows path,
#      so the built asset URLs come out wrong. MSYS_NO_PATHCONV=1 is set for
#      every build here.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT=boostmind-b052c
REGION=me-west1
SERVICE=workout-ai
API=https://workout-ai-463727469066.me-west1.run.app
SECRETS=ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,LEONARDO_API_KEY=LEONARDO_API_KEY:latest

WHAT="${1:-hosting}"
say() { printf '\n\033[1;35m▸ %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
ok()  { printf '\033[1;32m  ✓ %s\033[0m\n' "$*"; }

build_app() {
  say "PWA — typecheck and build"
  cd "$ROOT/workout-app"
  npx tsc -b || die "tsc failed — not deploying a broken build"
  MSYS_NO_PATHCONV=1 npx vite build
  ok "workout-app built"
}

build_hub() {
  say "marketing hub — manifest and build"
  [ -d "$ROOT/../marketing-hub" ] || die "marketing-hub not found next to BoostMind"
  cd "$ROOT/../marketing-hub"
  MSYS_NO_PATHCONV=1 npx vite build
  ok "marketing-hub built"
  # The hub reads src/data.json, generated by the manifest script that lives in
  # the session scratchpad. If a round is missing from the hub, that script did
  # not run — building here does not regenerate it.
  printf '    note: data.json is not regenerated here — rerun build_manifest.py if a round is missing\n'
}

deploy_hosting() {
  say "Firebase Hosting"
  cd "$ROOT"
  npx firebase deploy --only hosting --project "$PROJECT"
  ok "hosting deployed"
}

deploy_server() {
  say "Cloud Run — $SERVICE"
  gcloud auth print-access-token >/dev/null 2>&1 \
    || die "gcloud has no valid credentials. Run: gcloud auth login"
  cd "$ROOT/workout-app/server"
  node --check index.js     || die "index.js does not parse"
  node --check marketing.js || die "marketing.js does not parse"
  gcloud run deploy "$SERVICE" --source . --region "$REGION" --project "$PROJECT" \
    --allow-unauthenticated \
    --update-secrets="$SECRETS" \
    --memory=512Mi --cpu=1 --max-instances=3 --timeout=300 --quiet
  verify_server
}

verify_server() {
  say "verifying the live revision"
  local names
  names="$(gcloud run services describe "$SERVICE" --region "$REGION" --project "$PROJECT" \
           --format='value(spec.template.spec.containers[0].env[].name)')"
  printf '    secrets on revision: %s\n' "$names"
  for k in ANTHROPIC_API_KEY OPENAI_API_KEY LEONARDO_API_KEY; do
    case "$names" in
      *"$k"*) ok "$k present" ;;
      *) die "$k is MISSING from the live revision — the app will 503 on it" ;;
    esac
  done

  # A present secret is not a working one. Ask the endpoints themselves: a
  # 503 no_*_key is the failure this script exists to catch.
  local body
  body="$(curl -s -m 30 -X POST "$API/api/marketing/phrase" \
          -H 'content-type: application/json' \
          -d '{"uid":"user_6724","brief":"deploy check"}' || true)"
  case "$body" in
    *no_openai_key*) die "/phrase still reports no_openai_key" ;;
    *) ok "/phrase answered without a key error" ;;
  esac
}

case "$WHAT" in
  hosting) deploy_hosting ;;
  hub)     build_hub; deploy_hosting ;;
  app)     build_app; deploy_hosting ;;
  server)  deploy_server ;;
  verify)  verify_server ;;
  all)     build_app; build_hub; deploy_hosting; deploy_server ;;
  *) die "unknown target '$WHAT'. Use: hosting | hub | app | server | verify | all" ;;
esac

printf '\n\033[1;32m✓ done — %s\033[0m\n' "$WHAT"
